### ISSUE TITLE
32bits DLL from 64bits : passing pointers (C++)

### ISSUE THREAD

**Issue by MaxP92** [MSLNZ/msl-loadlib#10]
Hello,

Trying to pass pointers, I get the error 

> ctypes pointers cannot be pickled

So how to pass pointers to a C++ DLL `32bits`, in `64bits` Python (using `ctypes` or not) ?

**Comment by jborbely** [comment]
One cannot pass pointers from 64-bit Python to a 32-bit DLL because a 64-bit process cannot share the same memory space as a 32-bit process. All of your 32-bit pointers must be created (using `ctypes`) in your class that is a subclass of `Server32` and only the value that is stored at that address can be _pickled_ and returned to 64-bit Python for use in your 64-bit program.

**Comment by MaxP92** [comment]
Thanks it seems to work.

It might be a good idea to include it in the doc as it's not straigthforward ;)

**Comment by jborbely** [comment]
Thanks for the suggestion. I have included a comment in the docs for the C++ example.
