### ISSUE TITLE
Installation depends on pythonnet

### ISSUE THREAD

**Issue by romaia** [MSLNZ/msl-loadlib#11]
I am trying to install from pip on a fresh instalation of xubuntu but if fails when trying to install pythonnet.

I was under the impression that .net framework support was optional, but it appears that its a hard requirement.

**Comment by jborbely** [comment]
It is true that pythonnet should only be a requirement if installing on Windows.

The `setup.py` file uses features that were added in [PEP 508](https://www.python.org/dev/peps/pep-0508/) -- the `platform_system` marker:

```python
setup(
    ...
    install_requires=['py4j', 'pythonnet;platform_system=="Windows"'],
    ...
)
```

Perhaps the failure occurs because your version of `setuptools` is < 20.2, which is when [PEP 508](https://www.python.org/dev/peps/pep-0508/) was [supported](http://setuptools.readthedocs.io/en/latest/history.html#id284).

Could you please tell me which version of `setuptools` you are using and also let me know if upgrading it fixed the issue.

**Comment by romaia** [comment]
Yes, that might be the case. I was on a xubuntu 16.04 livecd, and according to [1], the latest update is 20.7 (I am not sure now on what version is on the livecd itself)

[1] https://packages.ubuntu.com/search?keywords=python-setuptools

I will mark it as closed since there appears nothing could/should be done for this.
