### ISSUE TITLE
server32-windows.exe not copied when package is installed on 32-bit python environment

### ISSUE THREAD

**Issue by gorzynsk** [MSLNZ/msl-loadlib#16]
'server32-windows.exe' file is not copied when package is installed on 32-bit python environment. Everything works flawlessly after manual copying of the file. Installation on 64-bit python works and copies the file mentioned.

My aim is to have a code which works during transition from 32-bit to 64-bit on both versions of environment as various teams sharing it can make the transition at different times.

**Comment by jborbely** [comment]
Yes, that was done intentionally. If someone installed the package using a 32-bit version of Python then there is no need to implement the client-server protocol because calling `LoadLibrary` is the only class that is useful. As you say, using the client-server protocol when the client is also running within 32-bit Python works, but it just adds unnecessary overhead and I was hoping to discourage this overhead by not making it available.

However, I do see that in a transition period from 32- to 64-bit Python that sharing the same underlying code base, that implements `Client64` and `Server32`, would make development easier.

Was creating this issue just an FYI or were you suggesting that wheels that include 'server32-windows.exe' should be made available on PyPI if pip is running within 32-bit Python? If you already manually copied the executable to the appropriate directory for each member of your team then did that solve your particular issue?

**Comment by jborbely** [comment]
As a way to get 'server32-windows.exe' included when your team pip-installs the package is to have them execute
```console
pip install -U https://github.com/MSLNZ/msl-loadlib/archive/v0.5.0.zip
```
Would that solve your issue or is there a particular reason that it should be available as a PyPI install?

I'm not against putting _win32_ wheels on PyPI it's just that I'll be traveling for the next couple of weeks and I don't know if I'll have the opportunity to do this any time soon.

**Comment by jborbely** [comment]
As of the latest release, v0.6.0, wheels for `win32` and `manylinux1_i686` are available on PyPI.
