### ISSUE TITLE
Why is having to define the client class even a thing?

### ISSUE THREAD

**Issue by fake-name** [MSLNZ/msl-loadlib#17]
I'm struggling to understand the point of having to define the entire ServerXX **and** ClientXX classes.

Basically, is there any reason you can't basically completely define your ClientXX class like:

```
import functools
from msl.loadlib import Client64

class ClassName(Client64):
	def __init__(self):
		super().__init__(module32='module_name', append_sys_path=os.path.dirname(__file__))

	def __getattr__(self, name):
		return functools.partial(self.request32, name)

```

The only thing that might need examining is properly passing exceptions from the client context back (and that appears to work fine), but I don't see any reason to bother duplicating all the methods from the client in the server.

**Comment by jborbely** [comment]
It is not possible to define a ServerXX class as you suggest. The reason is that the `Server32` and `Client64` classes perform different tasks. The `Server32` class loads a 32-bit library and it receives requests that are processed by the 32-bit library and then returns the result. The `Client64` class starts the 32-bit server and it sends requests to the server and returns the result from the server. Making one a subclass of the other would not make sense (at least not to me).

However, if you had asked _is there any reason you can't basically completely define your **_Client_** class like_ then my answer would have been _go ahead, no problem at all, the choice is yours_.

Suppose you wrote your `Client64` subclass like
```python
import os
from msl.loadlib import Client64

class ClassName(Client64):

    def __init__(self):
        super().__init__(module32='module_name', append_sys_path=os.path.dirname(__file__))

    def a(self, *args, **kwargs):
        return self.request32('a', *args, **kwargs)

    def b(self, *args, **kwargs):
        return self.request32('b', *args, **kwargs)

    def c(self, *args, **kwargs):
        return self.request32('c', *args, **kwargs)
    
    ...

    def z(self, *args, **kwargs):
        return self.request32('z', *args, **kwargs)

```
Then the equivalent code is (as you indicated)
```python
import os
import functools
from msl.loadlib import Client64

class ClassName(Client64):

    def __init__(self):
        super().__init__(module32='module_name', append_sys_path=os.path.dirname(__file__))

    def __getattr__(self, name):
        return functools.partial(self.request32, name)
```
and you get the same behaviour without duplicating the methods in the `Client64` subclass. This is perfectly fine if this is what you want to do. A `Server32Error` exception will be raised if you tried to access a method that does not exist on the `Server32` subclass instead of an `AttributeError`.

There are situations where you may want to duplicate methods in the `Client64` subclass, for example,

- you are writing an API for others to use and you want features like autocomplete or docstrings to be available in the IDE that the person using your API is using
- you want the Client to do error checking on the `*args`, `**kwargs` and on the result from the server because you want to have control over what `Exception` subclass is raised (if the server raises an exception then `Server32Error` is raised)
- a method from the Server returns a list and you want the corresponding Client method to return a numpy array

 but these choices are at the discretion of the person implementing the code.

**Comment by fake-name** [comment]
Yeah, whoops, swapped the two around.

**Comment by jborbely** [comment]
The examples were written in the way that they are in order to have the docstrings visible in the documentation of each method of a client which contains a link to the corresponding server method (and vice versa). 

Adding something like an _AutoClient_ is a good suggestion.

**Comment by fake-name** [comment]
I went a bit further, mostly motivated by the inability to print from the server;


```


class WrappedDll(Client64):
	def __init__(self):
		self.log = logging.getLogger("Main.DLL")
		self.rlog = logging.getLogger("Main.DLL-Remote")

		super().__init__(module32 = '<wrapped_file>',
			append_sys_path       = os.path.abspath(os.path.dirname(__file__)),
			append_environ_path   = os.path.abspath(os.path.dirname(__file__)))


	def __getattr__(self, name):
		return functools.partial(self.__try_unwrap_logging, name)

	def __try_unwrap_logging(self, *args, **kwargs):
		ret = self.request32(*args, **kwargs)
		if isinstance(ret, dict) and len(ret) == 2 and 'logs' in ret and 'ret' in ret:
			for level, message in ret["logs"]:
				getattr(self.rlog, level)(message)
			return ret['ret']
		return ret
```

```


class LogBuffer():
	def __init__(self):
		self.messages = []

	def critical(self, lstr, *args):
		self.messages.append(('critical', lstr % args))
	def error(self, lstr, *args):
		self.messages.append(('error', lstr % args))
	def warning(self, lstr, *args):
		self.messages.append(('warning', lstr % args))
	def info(self, lstr, *args):
		self.messages.append(('info', lstr % args))
	def debug(self, lstr, *args):
		self.messages.append(('info', lstr % args))

	def pop_logs(self):
		ret = self.messages
		self.messages = []
		return ret

class Cpp32(Server32):
	def __init__(self, host, port, quiet, **kwargs):
		self.log = LogBuffer()
		super().__init__(
				path    = os.path.join(os.path.dirname(__file__), '<dll_name>'),
				libtype = 'windll',
				host    = host,
				port    = port,
				quiet   = quiet,
			)


	def __getattr__(self, name):
		fname = "_" + name

		if hasattr(self, fname):
			tgt_func = getattr(self, fname)

			def fun(*args, **kwargs):
				assert tgt_func is not None, "Function %s not found. Searched as %s." % (
					name, fname)

				ret = tgt_func(*args, **kwargs)

				logs = self.log.pop_logs()

				return {
						'logs' : logs,
						'ret'  : ret,
					}

			return fun

		raise RuntimeError("Attribute %s missing!" % (fname, ))

```

This gives you automatic logging proxying back from the client. Actually, it'd be even neater to forward anything written to stdout by the server back through the pipe, but this was easier in my application. 

Function names are access indirectly (e.g. server `Func()` needs to be defined as `_Func()`, but is accessed as `client.Func()`) to allow the log injection to work. This could probably also be worked around by overriding `__getattribute__`, rather then `__getattr__`, but again the above was written because I need to use it, rather then as a ideal implementation.

**Comment by jborbely** [comment]
> I'd assume something somewhere is directly using the truthyness of append_environ_path, and therefore ignoring a empty string (as opposed to None), but a cursory check didn't yield a probable cause.

That's correct... in `start_server32.py` there's a `if path:` check before appending _path_.

I added a `.. tip::` directive to the docs showing how to use `__getattr__` and explained why you may or may not want to use this shortcut for all/some of the client methods. Thanks for the suggestion.

I decided not to add an _AutoClient_ class as part of the API because I figured that, even in your own example you would have not used my _AutoClient_ class because you have a custom `__try_unwrap_logging` method that you want to call. I think that there are too many ways that someone could subclass `Client64` and that decision should be in the hands of the end user.
