### ISSUE TITLE
repo server32 not a valid exexutable

### ISSUE THREAD

**Issue by amarco** [MSLNZ/msl-loadlib#36]
I did a git pull/install and when I run my code I get an error which oddly enough does not happen if I build my own 32server.

----------------------snip start
Exception has occurred: ConnectionTimeoutError
Timeout after 10.0 seconds. Could not connect to 127.0.0.1:18879
Importing 'CobraPyServer' on the 32-bit server raised the following exception:

Traceback (most recent call last):
  File "PyInstaller\loader\pyimod03_ctypes.py", line 77, in __init__
  File "ctypes\__init__.py", line 376, in __init__
OSError: [WinError 193] %1 is not a valid Win32 application

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "start_server32.py", line 151, in main
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ma\OneDrive - RWDI\Documents\Visual Studio Code\Projects\CobraPy\CobraPyServer.py", line 7, in <module>
    import numpy as np
  File "c:\WinPython\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\numpy\__init__.py", line 138, in <module>
    from . import _distributor_init
  File "c:\WinPython\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "PyInstaller\loader\pyimod03_ctypes.py", line 79, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll 'c:\\WinPython\\WPy64-31110\\python-3.11.1.amd64\\Lib\\site-packages\\numpy\\.libs\\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll'. Most likely this dynlib/dll was not found when the application was frozen.

Cannot start the 32-bit server.
  File "C:\Users\ma\OneDrive - RWDI\Documents\Visual Studio Code\Projects\CobraPy\CobraPy.py", line 7, in __init__
    super(CobraPy, self).__init__(module32='CobraPyServer.py')
  File "C:\Users\ma\OneDrive - RWDI\Documents\Visual Studio Code\Projects\CobraPy\Example.py", line 13, in <module>
    cobraPy = CobraPy()
              ^^^^^^^^^
msl.loadlib.exceptions.ConnectionTimeoutError: Timeout after 10.0 seconds. Could not connect to 127.0.0.1:18879
Importing 'CobraPyServer' on the 32-bit server raised the following exception:

Traceback (most recent call last):
  File "PyInstaller\loader\pyimod03_ctypes.py", line 77, in __init__
  File "ctypes\__init__.py", line 376, in __init__
OSError: [WinError 193] %1 is not a valid Win32 application

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "start_server32.py", line 151, in main
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ma\OneDrive - RWDI\Documents\Visual Studio Code\Projects\CobraPy\CobraPyServer.py", line 7, in <module>
    import numpy as np
  File "c:\WinPython\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\numpy\__init__.py", line 138, in <module>
    from . import _distributor_init
  File "c:\WinPython\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "PyInstaller\loader\pyimod03_ctypes.py", line 79, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll 'c:\\WinPython\\WPy64-31110\\python-3.11.1.amd64\\Lib\\site-packages\\numpy\\.libs\\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll'. Most likely this dynlib/dll was not found when the application was frozen.

Cannot start the 32-bit server.
--------------------------------------------snip end

How can this be resolved?

Marco

**Comment by jborbely** [comment]
You are correct, a 32-bit version of numpy is not bundled with the default 32-bit server.

I suppose you are asking whether numpy _should_ be included by default (i.e., included with a ``pip install``) since you have previously demonstrated (in issue #34) that it _can_ be included by refreezing the server in a custom configuration.

Below are just some reasons why, so far, it has not been bundled by default (but open to hear comments why it should be)

1) There are concerns about pickling a 32-bit `ndarray` and unpickling the 64-bit variant (or vice versa). While it may work in some cases, it may not always work perfectly. Obviously there is no problem if it works, a bit annoying if an error is raised, but, if the values in the array get silently changed due to an overflow (e.g., np.int8(128) = -128) or different pointer lengths then that is dangerous. Knowing the fine details of the `pickle` module and `ndarray`'s are required, which I don't know.

2) Using the `np.save` and `np.load` functions may be better to save an `ndarray` to a binary file in .npy format. The `allow_pickle` kwarg in the [np.save](https://numpy.org/doc/stable/reference/generated/numpy.save.html) function talks about caveats when using `pickle` with an `ndarray`. This is related to (1) and the fact that `Client64` and `Server32` may be using different versions of Python and different versions of numpy.

3) Bundling 32-bit numpy will increase the size of the frozen server32 executable. Some people may not want the bloated server32 file if they are not using numpy.

4) Using numpy to allocate memory for a shared-library parameter is convenient, but not required because `ctypes` can to it.

5) An alternate way to deal with `ndarray`'s is to use the `ndarray.tolist()` method as discussed [here](https://msl-loadlib.readthedocs.io/en/stable/tutorials_cpp.html#arrays). This conversion adds overhead, but there already is a lot of overhead in the client-server procedure, namely: pickling the request to a file, calling the server, loading the pickled request from a file, executing the 32-bit function, picking the response to a file, loading the pickled response from a file, checking the response for an error, returning the response.

**Comment by amarco** [comment]
Thankyou for your summary and for this tool in general.
I was trying to make the wrapper without numpy but being a bit of newbie I got really turned around with trying to pass back and forth float** data and float* data.
In the end I was able to use numpy and its ctypes and things worked well in a all 32bit environment.
I then need to have things work in a 64/32 bit situation and then found msl-loadlib, which came to my rescue 😊
I am ok making my own server32-windows.exe with the components and your change to the code to allow an alternate location from which to load the file worked for me as I could distribute the exe with my python code.
I downloaded the lates main code and altered my client code to reflect the change and now I am getting a cannot find file error show below. The exe is located in the same folder as my py files.

File "C:\Users\ma\OneDrive - RWDI\Documents\Visual Studio Code\Projects\CobraPy\CobraPy.py", line 8, in __init__
    super(CobraPy, self).__init__(module32='CobraPyServer.py',server32_dir=os.path.dirname(__file__))
  File "c:\WinPython\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\msl\loadlib\client64.py", line 228, in __init__
    utils.wait_for_server(host, port, timeout)
  File "c:\WinPython\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\msl\loadlib\utils.py", line 295, in wait_for_server
    raise ConnectionTimeoutError(
msl.loadlib.exceptions.ConnectionTimeoutError: Timeout after 10.0 seconds. Could not connect to 127.0.0.1:29935
Instantiating the 32-bit server raised the following exception:
  FileNotFoundError: [WinError 2] The system cannot find the file specified
Cannot start the 32-bit server.

Am I doing something wrong in my implementation?

Marco

**Comment by jborbely** [comment]
You can see an example [here](https://msl-loadlib.readthedocs.io/en/stable/_modules/msl/examples/loadlib/cpp32.html#Cpp32.scalar_multiply) for how to deal with `float*` arguments and [here](https://msl-loadlib.readthedocs.io/en/stable/_modules/msl/examples/loadlib/fortran32.html#Fortran32.matrix_multiply) for using `float**` (although this example uses a FORTRAN library, so matricies are in column-major order instead of row-major order, but the concept is the same). Then you can remove the need for numpy. Your choice.

Are you able to paste some of the `CobraPyServer.py` file here? In particular, the `__init__` method of the `Server32` subclass. This is not a _"where is the server32?"_ error but in the `__init__` method you must be loading a file (probably the DLL) that cannot be found.

**Comment by amarco** [comment]
class CobraPy(Client64):
    def __init__(self):
        server_dir = os.path.dirname(__file__)
        server_mod = os.path.join(server_dir,'CobraPyServer.py')
        super(CobraPy, self).__init__(module32=server_mod,server32_dir=server_dir)


class CobraPyServer(Server32):
    def __init__(self, host, port, **kwargs):
        super(CobraPyServer, self).__init__('pmDevCtrlInterface.dll', 'windll', host, port)
        self._stdout=[]
        self.print("Dll services initiated using process:{0}".format(Server32.version()))

Above are the inits of my two class files, the pmDevCtrlInterfac lives in C:\Windows\SysWOW64

I will have a look at the all ctype approach, and perhaps make it a longer goal 😊

Marco

**Comment by jborbely** [comment]
Some suggestions:

1) You mentioned in another issue that you intend to distribute your code. Did you distribute the DLL with your code? (You don't need to actually answer this, I'm just stating the _dummy_ check).

2) Is `C:\Windows\SysWOW64` in the `PATH` environment variable of the computer you are running on? If not, add it to `PATH` or add it to the `append_environ_path` kwarg of `CobraPy`, e.g.,

```python
class CobraPy(Client64):
    def __init__(self):
        server_dir = os.path.dirname(__file__)
        server_mod = os.path.join(server_dir,'CobraPyServer.py')
        super(CobraPy, self).__init__(module32=server_mod,server32_dir=server_dir, append_environ_path=r'C:\Windows\SysWOW64')
```

3) Instead of doing (2), be explicit with the location of the DLL in `CobraPyServer`
```python
class CobraPyServer(Server32):
    def __init__(self, host, port, **kwargs):
        super(CobraPyServer, self).__init__(r'C:\Windows\SysWOW64\pmDevCtrlInterface.dll', 'windll', host, port)
        self._stdout=[]
        self.print("Dll services initiated using process:{0}".format(Server32.version()))
```

4) Temporarily simplify `CobraPyServer` by commenting the `self.print` line (this way only msl-loadlib code is being run, since I don't know what calling `self.print` does). _As a side comment, you can replace `Server32.version()` with ``f'Python {sys.version}'`` since it will be exactly the same result but much faster._

```python
class CobraPyServer(Server32):
    def __init__(self, host, port, **kwargs):
        super(CobraPyServer, self).__init__('pmDevCtrlInterface.dll', 'windll', host, port)
        self._stdout=[]
        # self.print("Dll services initiated using process:{0}".format(Server32.version()))
```

**Comment by amarco** [comment]
Thanks JS

I started by removing the print statement since by default windows os always has a path to syswow by default and things loaded as expected.
Actually I removed the entire print polling mechanism as it was an attempt at getting debug output. Same with the version statement, I removed it as well as I was experimenting.

Thanks again for your insights it was very helpful.

I think now that I have something working I will see if I can refactor to remove numpy as a dependency 😊 as it seems natural now.

Marco
