### ISSUE TITLE
missing package on PyPI?

### ISSUE THREAD

**Issue by 1oglop1** [MSLNZ/msl-loadlib#4]
Hi, I was wondering what are the difficulties that this package is not on PyPI?
https://pypi.org
or
https://pypi.python.org

If you guys need a hand with that, let me know, because it looks like this package will be core of our application.

Thanks

**Comment by jborbely** [comment]
The only reason why I haven't done this yet is simply because I wrote the package for personal use and up until reading your message there hasn't been a request/need to upload it to PyPI.

I will try to find the time to do this as soon as possible.

The following option is certainly not ideal based on your message, but, as an alternative option for installing the package from the command line you can also use the [msl-package-manager](https://pypi.org/project/msl-package-manager/)

Thanks for your interest in this package.

**Comment by jborbely** [comment]
Wheels for 64-bit Windows/Linux are now available on PyPI [here](https://pypi.python.org/pypi/msl-loadlib)

**Comment by 1oglop1** [comment]
awesome thank you!

**Comment by webknjaz** [comment]
@jborbely mind putting into play CIs w/ tests and automatic building and publishing of platform-specific wheels?

**Comment by jborbely** [comment]
@webknjaz could you please open a new issue about CI and explain a little bit more about the reason why you are requesting this. Thanks.

**Comment by webknjaz** [comment]
I thought it's got platform-specific code. But now I see that it's `pythonnet` needing to do this :)

**Comment by webknjaz** [comment]
@jborbely But it's still useful for you to have automated distribution building/publishing: I normally configure CI to deploy dist to PYPI automatically from `git tag`ged commits. Also, the version is not stored in the code, but just read from git tag.
I could tell you more if you'd like. I don't really mind if you have this, but normally I'm trying to automate and simplify things, because it's getting annoying to do lots of same manual stuff across lots of open-source repos I happen to maintain or support :)

**Comment by jborbely** [comment]
@webknjaz I appreciate the encouragement to use CI for automated testing and deployment. This is indeed a very useful tool that I intend to use in the (hopefully not too distant) future which will help simplify things.
